/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antold;

import com.sun.imageio.plugins.jpeg.JPEG;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author Win 8
 */
public class xRoll extends javax.swing.JFrame {

    /**
     * Creates new form xRoll
     */
    
    String data;
    String hash; 
    String SeverSeedSHA;
    String lastServerSeed;
    String resultado;
    String xResultado;
    String nonce;
    String hex;
    String decimal;
    String result;
    String numberRoll;
    long l;
    double d;
    int a;
    

    public xRoll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editText_clientSeed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editText_serverSeedSHA = new javax.swing.JTextField();
        button_1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editText_lastServerSeed = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        editText_nonce = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textView_Resultado = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        editText_numberRoll = new javax.swing.JTextField();
        button_2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        editText_decimal = new javax.swing.JTextField();
        editText_result = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        button_sair = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        editText_hex = new javax.swing.JTextField();
        button_restart = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        textView_Resultado1 = new javax.swing.JLabel();
        editText_resultado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textView_Resultado2 = new javax.swing.JLabel();
        textView_Resultado3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("xRoll - Try Catch in freebitco.in ");
        setBackground(java.awt.Color.black);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Croissant One", 1, 11)); // NOI18N
        jLabel1.setText("INSERT HERE A RANDOM NAME FOR \"CLIENT SEED\" IN FREEBITCO.IN. Most be the same and have 16 Characters, change before each roll");

        editText_clientSeed.setFont(new java.awt.Font("Croissant One", 0, 14)); // NOI18N
        editText_clientSeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText_clientSeed.setText("RandomClientSeed");
        editText_clientSeed.setToolTipText("");
        editText_clientSeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editText_clientSeedActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Croissant One", 1, 14)); // NOI18N
        jLabel5.setText("CLIENT SEED");

        jLabel6.setFont(new java.awt.Font("Croissant One", 1, 14)); // NOI18N
        jLabel6.setText("Server Seed Hash (SHA-256)");

        editText_serverSeedSHA.setFont(new java.awt.Font("Croissant One", 0, 14)); // NOI18N
        editText_serverSeedSHA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText_serverSeedSHA.setToolTipText("");
        editText_serverSeedSHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editText_serverSeedSHAActionPerformed(evt);
            }
        });

        button_1.setBackground(new java.awt.Color(255, 204, 0));
        button_1.setFont(new java.awt.Font("Croissant One", 0, 12)); // NOI18N
        button_1.setText("BEGIN NOW");
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Croissant One", 2, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Complete this 3 Box Text fisrt before begin - Write something with 16 char in Client Seed box ");

        jLabel9.setFont(new java.awt.Font("Croissant One", 1, 14)); // NOI18N
        jLabel9.setText("LAST Server Seed");

        editText_lastServerSeed.setFont(new java.awt.Font("Croissant One", 0, 14)); // NOI18N
        editText_lastServerSeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText_lastServerSeed.setToolTipText("");
        editText_lastServerSeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editText_lastServerSeedActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Croissant One", 1, 14)); // NOI18N
        jLabel10.setText("NONCE");

        editText_nonce.setFont(new java.awt.Font("Croissant One", 0, 14)); // NOI18N
        editText_nonce.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText_nonce.setToolTipText("");
        editText_nonce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editText_nonceActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Croissant One", 1, 14)); // NOI18N
        jLabel11.setText("WAITING FOR RESULT - Insert the Nounce Number and CALCULE");

        textView_Resultado.setFont(new java.awt.Font("Croissant One", 1, 18)); // NOI18N
        textView_Resultado.setForeground(new java.awt.Color(0, 51, 204));
        textView_Resultado.setText("Made in 25/05/2019");

        jLabel12.setFont(new java.awt.Font("Croissant One", 1, 14)); // NOI18N
        jLabel12.setText("COMPUTED HMAC (SHA-512)");

        editText_numberRoll.setEditable(false);
        editText_numberRoll.setFont(new java.awt.Font("Croissant One", 0, 18)); // NOI18N
        editText_numberRoll.setForeground(new java.awt.Color(255, 0, 0));
        editText_numberRoll.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText_numberRoll.setText("*****");
        editText_numberRoll.setToolTipText("");
        editText_numberRoll.setOpaque(false);
        editText_numberRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editText_numberRollActionPerformed(evt);
            }
        });

        button_2.setBackground(new java.awt.Color(255, 204, 0));
        button_2.setFont(new java.awt.Font("Croissant One", 0, 12)); // NOI18N
        button_2.setText("MAKE MATH");
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Croissant One", 1, 11)); // NOI18N
        jLabel14.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel15.setFont(new java.awt.Font("Croissant One", 1, 14)); // NOI18N
        jLabel15.setText("DECIMAL VALUE OF HMAC SHA-512");

        editText_decimal.setEditable(false);
        editText_decimal.setBackground(new java.awt.Color(255, 255, 255));
        editText_decimal.setFont(new java.awt.Font("Croissant One", 0, 14)); // NOI18N
        editText_decimal.setForeground(new java.awt.Color(0, 0, 255));
        editText_decimal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText_decimal.setText("***************");
        editText_decimal.setToolTipText("");
        editText_decimal.setOpaque(false);
        editText_decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editText_decimalActionPerformed(evt);
            }
        });

        editText_result.setEditable(false);
        editText_result.setBackground(new java.awt.Color(255, 255, 255));
        editText_result.setFont(new java.awt.Font("Croissant One", 0, 14)); // NOI18N
        editText_result.setForeground(new java.awt.Color(0, 0, 204));
        editText_result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText_result.setText("***********************");
        editText_result.setToolTipText("");
        editText_result.setOpaque(false);
        editText_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editText_resultActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Croissant One", 1, 14)); // NOI18N
        jLabel16.setText("FINAL RESULT OF MATH ");

        button_sair.setBackground(new java.awt.Color(255, 0, 0));
        button_sair.setFont(new java.awt.Font("Croissant One", 1, 12)); // NOI18N
        button_sair.setText("QUIT - EXIT");
        button_sair.setActionCommand("");
        button_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sairActionPerformed(evt);
            }
        });

        button_3.setBackground(new java.awt.Color(255, 204, 0));
        button_3.setFont(new java.awt.Font("Croissant One", 0, 12)); // NOI18N
        button_3.setText("FINAL RESULT");
        button_3.setActionCommand("");
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(0, 51, 255));
        jLabel17.setFont(new java.awt.Font("Croissant One", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 204));
        jLabel17.setText("<-- MOST NEAR NEXT ROOL NUMBER");

        editText_hex.setEditable(false);
        editText_hex.setBackground(new java.awt.Color(255, 255, 255));
        editText_hex.setFont(new java.awt.Font("Croissant One", 0, 14)); // NOI18N
        editText_hex.setForeground(new java.awt.Color(0, 0, 255));
        editText_hex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText_hex.setText("************");
        editText_hex.setToolTipText("");
        editText_hex.setOpaque(false);
        editText_hex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editText_hexActionPerformed(evt);
            }
        });

        button_restart.setBackground(new java.awt.Color(255, 255, 255));
        button_restart.setFont(new java.awt.Font("Croissant One", 1, 12)); // NOI18N
        button_restart.setText("RESTART");
        button_restart.setActionCommand("");
        button_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_restartActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Croissant One", 1, 11)); // NOI18N
        jLabel18.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        textView_Resultado1.setFont(new java.awt.Font("Croissant One", 1, 24)); // NOI18N
        textView_Resultado1.setForeground(new java.awt.Color(255, 0, 0));
        textView_Resultado1.setText("----->>>");
        textView_Resultado1.setToolTipText("");

        editText_resultado.setEditable(false);
        editText_resultado.setFont(new java.awt.Font("Croissant One", 0, 14)); // NOI18N
        editText_resultado.setForeground(new java.awt.Color(0, 0, 255));
        editText_resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editText_resultado.setText("*********************************************");
        editText_resultado.setToolTipText("");
        editText_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editText_resultadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Croissant One", 1, 14)); // NOI18N
        jLabel7.setText("If Like \"Server Seed Hash\" then Go");

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Croissant One", 1, 11)); // NOI18N
        jLabel19.setText(" ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        textView_Resultado2.setFont(new java.awt.Font("Croissant One", 1, 24)); // NOI18N
        textView_Resultado2.setForeground(new java.awt.Color(255, 0, 0));
        textView_Resultado2.setText("<<<---");
        textView_Resultado2.setToolTipText("");

        textView_Resultado3.setFont(new java.awt.Font("Croissant One", 1, 24)); // NOI18N
        textView_Resultado3.setForeground(new java.awt.Color(255, 0, 0));
        textView_Resultado3.setText("<<<---");
        textView_Resultado3.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textView_Resultado1)
                                .addGap(36, 36, 36)
                                .addComponent(textView_Resultado))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(editText_serverSeedSHA, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(editText_clientSeed, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18)
                                            .addComponent(editText_nonce, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(textView_Resultado3)
                                            .addGap(26, 26, 26)
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(editText_hex, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(textView_Resultado2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(26, 26, 26)
                                            .addComponent(editText_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(editText_lastServerSeed, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(button_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_sair)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(editText_numberRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editText_decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editText_result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(button_restart)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(button_3)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editText_clientSeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editText_serverSeedSHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editText_lastServerSeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textView_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textView_Resultado1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editText_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editText_hex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editText_nonce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textView_Resultado2)
                        .addComponent(textView_Resultado3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editText_decimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editText_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editText_numberRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_restart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editText_clientSeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editText_clientSeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editText_clientSeedActionPerformed

    private void editText_serverSeedSHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editText_serverSeedSHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editText_serverSeedSHAActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        // TODO add your handling code here:
        SeverSeedSHA = null;
        resultado = null;
        editText_resultado.setText("*********************************************");
        
        try{
          data = editText_lastServerSeed.getText().toString();         
          xRoll sj = new xRoll();
          hash = sj.getSHA256Hash(data);
          resultado = hash;
          SeverSeedSHA = editText_serverSeedSHA.getText().toString();
            
          editText_resultado.setText(resultado.toLowerCase());
          
          if (SeverSeedSHA.equalsIgnoreCase(resultado)){
              textView_Resultado.setText("SUCCESS... CONTINUOUS!");
          } else {
              textView_Resultado.setText("STOP... GAME FRAUD!");
          }
        }
        catch (Exception E){
            JOptionPane.showMessageDialog(null, "ERROR... RESTART!");
        }
    }//GEN-LAST:event_button_1ActionPerformed

    private void editText_lastServerSeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editText_lastServerSeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editText_lastServerSeedActionPerformed

    private void editText_nonceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editText_nonceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editText_nonceActionPerformed

    private void editText_numberRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editText_numberRollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editText_numberRollActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
        // TODO add your handling code here:
        
        Mac sha512_HMAC = null;
        result = null;
            
        nonce = editText_nonce.getText().toString(); 
        String serverSeed = editText_lastServerSeed.getText().toString();
        serverSeed = nonce + ":" + serverSeed + ":" + nonce;
        String key =  editText_clientSeed.getText().toString();
        key = nonce + ":" + key + ":" + nonce;

        try{
            byte [] byteKey = key.getBytes("UTF-8");
            final String HMAC_SHA512 = "HmacSHA512";
            sha512_HMAC = Mac.getInstance(HMAC_SHA512);      
            SecretKeySpec keySpec = new SecretKeySpec(byteKey, HMAC_SHA512);
            sha512_HMAC.init(keySpec);
            byte [] mac_data = sha512_HMAC.
             doFinal(serverSeed.getBytes("UTF-8"));
            //result = Base64.encode(mac_data);
            result = bytesToHex(mac_data);
            System.out.println(result);
        } catch (UnsupportedEncodingException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (InvalidKeyException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }finally{
            editText_hex.setText(result.substring(0,8));
        }
        
    }//GEN-LAST:event_button_2ActionPerformed

    private void editText_decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editText_decimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editText_decimalActionPerformed

    private void editText_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editText_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editText_resultActionPerformed

    private void button_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sairActionPerformed
        // TODO add your handling code here:
            lastServerSeed = editText_lastServerSeed.getText().toString();
             JOptionPane.showMessageDialog(null, "THANK YOU FOR PURCHASE!");
        System.exit(0);
    }//GEN-LAST:event_button_sairActionPerformed

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
        // TODO add your handling code here:
    hex = editText_hex.getText().toString();
    l = Long.parseLong(hex, 16);
    editText_decimal.setText(Long.toString(l));
    d = l / 429496.7295;
    editText_result.setText(Double.toString(d));
    a = (int)d + 1;
    editText_numberRoll.setText(Integer.toString(a  ));
 
    }//GEN-LAST:event_button_3ActionPerformed

    private void editText_hexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editText_hexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editText_hexActionPerformed

    private void button_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_restartActionPerformed
        // TODO add your handling code here:
             JOptionPane.showMessageDialog(null, "Server Seed Hash (SHA-256)\n" + SeverSeedSHA + "\n\n"
                     + "LAST Server Seed\n" + SeverSeedSHA + "\n\n" + "Hexadecimal Result\n" + resultado
                     + "\n\nThis is value Decimal and final Result:\n" 
                     + l + "\n\n" + l + " / " + "429496.7295 = " + d + "\n\n");
            
    editText_clientSeed.setText("");
    editText_decimal.setText("*****************");
    editText_hex.setText("************");
    editText_lastServerSeed.setText("");
    editText_nonce.setText("");
    editText_numberRoll.setText("*****");
    editText_resultado.setText("*********************************************s");
    editText_result.setText("************************************************");
    editText_serverSeedSHA.setText("");
            
    }//GEN-LAST:event_button_restartActionPerformed

    private void editText_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editText_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editText_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xRoll().setVisible(true);
            }
        });     
        
       /*
        JOptionPane.showMessageDialog(null, "This is demo version, run just 5 second");
        Thread.sleep( 5 * 1000 ); // aguarda 5segundos
        JOptionPane.showMessageDialog(null, "Demo Version, purchase the programe with 0.00050000");
        System.exit(0);
        */
    }

    
     /**
     * Returns a hexadecimal encoded SHA-256 hash for the input String.
     * @param data
     * @return 
     */
    private String getSHA256Hash(String data) {
        String result = null;
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(data.getBytes("UTF-8"));
            return bytesToHex(hash); // make it printable
        }catch(Exception ex) {
            ex.printStackTrace();
        }
        return result;
    }
     
    /**
     * Use javax.xml.bind.DatatypeConverter class in JDK to convert byte array
     * to a hexadecimal string. Note that this generates hexadecimal in upper case.
     * @param hash
     * @return 
     */
    private String  bytesToHex(byte[] hash) {
        return DatatypeConverter.printHexBinary(hash);
    }
    
    public static String bytesToHexa(byte[] bytes) {
        final  char[] hexArray = "0123456789ABCDEF".toCharArray();
        char[] hexChars = new char[bytes.length * 2];
        for ( int j = 0; j < bytes.length; j++ ) {
            int v = bytes[j] & 0xFF;
            hexChars[j * 2] = hexArray[v >>> 4];
            hexChars[j * 2 + 1] = hexArray[v & 0x0F];
        }
        return new String(hexChars);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_restart;
    private javax.swing.JButton button_sair;
    private javax.swing.JTextField editText_clientSeed;
    private javax.swing.JTextField editText_decimal;
    private javax.swing.JTextField editText_hex;
    private javax.swing.JTextField editText_lastServerSeed;
    private javax.swing.JTextField editText_nonce;
    private javax.swing.JTextField editText_numberRoll;
    private javax.swing.JTextField editText_result;
    private javax.swing.JTextField editText_resultado;
    private javax.swing.JTextField editText_serverSeedSHA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel textView_Resultado;
    private javax.swing.JLabel textView_Resultado1;
    private javax.swing.JLabel textView_Resultado2;
    private javax.swing.JLabel textView_Resultado3;
    // End of variables declaration//GEN-END:variables
}
